* 云平台的意见建议
** 前端页面和响应速度
前端页面作为用户操作的直接交互界面，对于用户体验非常重要。
而响应速度也是提高用户体验的重要途径。
在保证平台功能的实现的同时不能忽略了这两方面的优化。
** 混合云基础架构
*** 平台统一化
云管平台是一种管理公有云、私有云和混合云环境的整合性产品，
应具备的最小功能范围包括自服务界面、提供系统镜像、计量和计费，以及通过建立策略
实现一定程度的负载优化。更高级的功能还包括整合外部企业管理系统，包括服务目录、支
持存储和网络资源配臵，允许通过服务代理实现的增强资源管理，
并提供高级监控功能以改进客户应用性能和可用性。
*** 高密度高效率
在虚拟机配臵（内存、vCPU）和资源超售（常见于公有云）比
例等因素不变的情况下，物理服务器采用的 CPU 内核越多、配备的
内存容量越大，同样数量的服务器所能提供的虚拟机数量也就越多。
CPU 多核化在混合云架构中表现为：公有云平台可以从同样数
量的物理服务器中获得更多的用户，从而增加收入，或者降低虚拟机
的价格；私有云平台服务器的内核及内存越多，意味着可以用更少的
服务器来满足业务需求，或者同样数量的服务器可以承载更多业务，
这些自然会降低企业 IT 的 CapEx 和 OpEx，从而降低 TCO（总拥有
成本）。以英特尔最新推出的至强可扩展处理器为例，其铂金版 8160
处理器集成 24 个物理内核，支持的虚拟机数量较前几代有好几倍的
提升
*** 软件定义化
超融合架构（Hyper-Converged Infrastructure, HCI）融合了计算虚
拟化与分布式软件定义存储，以软硬件一体的模块化单元出现，便于
快速部署，并大大简化运维，从而可以降低企业的费用支出。基于上
述特点，超融合架构被越来越多地作为私有云或混合云的交付手段。
例如，微软的 Azure Stack 一体机就基于超融合架构，并将其作为混
合云中的私有云部署方案。

** 应用场景
混合云的主要应用场景有负载扩充、灾难恢复、数据备份、应用部署、开发测试生产部署等。
** 总结,建议 
目前咋们搭建的混合云平台应该还只是封装私有云和共有云提供的 api 吧，只提供了一些简单管理和统计功能。
(平台一直崩溃具体功能看不了，只能根据前两天看的说一下.）

为了平台的完善，以及适用于客户的需求。
在我们具体的平台搭建过程中，如何将这些架构落实,实现平台统一化中的功能，
如何实现高密度高效率以及软件定义化，如何对客户提出的需求和应用场景进行具体优化，
应为我们具体详尽的考虑内容。
